name: Update gist with WakaTime stats2
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: waka-box
        uses: matchai/waka-box@v4.0.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 7ae61dd5e95e319516067a2b3e6ade9f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
